# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28aa2769c441f078a39b5bc4f40ab1ed14864bc929f36afec0fda225669d3000e1913139ac9e2d0d6ebac2ed25ba42287390c33172583c99f5230a902396cab3

test:
  secret_key_base: 3ad81f6cffaad3ce9afed1a5cc31f1e84317111f09d12605d086620e9e4cb32b4234fe56013a24c4605d24077ef15b482cdf8dc284226e7d59d5f6b242187d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
